### ISSUE TITLE
Add parameter-less constructor to support XmlSerializer

### ISSUE THREAD

**Issue by dgiddins** [xyncro/semver.net#1]
Please add a parameter-less constructor to SemVer to allow serialization with XmlSerializer

**Comment by kolektiv** [comment]
HI @daffers - I'll take a look at this one and make sure it's simple - if it is then I'll fix this shortly and update here. Apologies for the (very long) delay in replying, GitHub didn't let me know on this one...

**Comment by kolektiv** [comment]
Hi @daffers - I've looked at this and it seems like SemanticVersion already has a default constructor - at least, it seems to work. Are you using SemVer directly? I've not had a chance to try directly with XmlSerializer - is there a little test case you could send me which would show the issue? If so I'll try and fix it promptly.
