### ISSUE TITLE
TryParse Does not follow .Net conventions

### ISSUE THREAD

**Issue by twhitbeck** [xyncro/semver.net#2]
TryParse typically returns `bool` and outputs the result. You've got it backwards. I'd like to fix, but not familiar with F#.

**Comment by kolektiv** [comment]
Hi @twhitbeck - yes you're right, I've not been writing much non-F# lately. I'll fix this, it'll only take a moment. Sorry for the slow response, for some reason GitHub doesn't appear to be emailing me issues!

Thanks for reporting, I'll update this when it's fixed :+1:

**Comment by kolektiv** [comment]
Hi again @twhitbeck - I've pushed a new package up to Nuget with, theoretically, the correct formulation of TryParse! If you get a chance see if that's better for you, and close this if so (I'll close it myself if I don't hear from you for a while!) Thanks again for reporting.
