### ISSUE TITLE
Handle version starting with "v"

### ISSUE THREAD

**Issue by aloisdg** [xyncro/semver.net#4]
Hello,

SemVer.Net throw an exception if a version starts with a "v". `0.0.1` is valid but `v0.0.1`isn't.
As far as i know, SemVer allows this "v" (see [semver.org](http://semver.org/spec/v1.0.0.html)).
Can you handle it?

Thank you.

**Comment by kolektiv** [comment]
Hi!

I'm sorry I hadn't seen this issue raised before, I'm sorry it looks like it's been ignored, but definitely not the intention. My understanding of the "v" prefix is that it applies to a tag in a version control system not the version itself... But I could be wrong. What do you think?

**Comment by aloisdg** [comment]
I dont know. I am not sure. You can find a "v2.0.0" or a "v1.0.0" with no tag.

**Comment by mexx** [comment]
FYI: https://github.com/mojombo/semver/pull/234

**Comment by aloisdg** [comment]
@mexx so it is not. Good to know. You fixed the issue.

From the official FAQ:

> **Is "v1.2.3" a semantic version?**
> 
> No, "v1.2.3" is not a semantic version. However, prefixing a semantic version with a "v" is a common way (in English) to indicate it is a version number. Abbreviating "version" as "v" is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case "v1.2.3" is a tag name and the semantic version is "1.2.3".

**Comment by kolektiv** [comment]
Ah! Thanks @mexx - and thanks @aloisdg for reporting - even if it's not a bug it's good to have it clarified! :)

**Comment by aloisdg** [comment]
Yes. Glad to learn something new.
